from playwright.async_api import async_playwright
import asyncio
import requests
 
 
async def main():
   async with async_playwright() as pw:
       browser = await pw.chromium.launch(
          proxy={
              “server”: "http://pr.oxylabs.io:7777",
              "username": "USERNAME",
              "password": "PASSWORD"
              },
          headless=False
      )
 
       page = await browser.new_page()
       await page.goto('https://money.usnews.com/credit-cards/alliant-credit-union/alliant-cashback-visa-signature-card')
       await page.wait_for_timeout(5000)
 
       all_images = await page.query_selector_all('img')
       images = []
       for i, img in enumerate(all_images):
           image_url = await img.get_attribute("src")
           content = requests.get(image_url).content
           with open(“image_{}.svg”.format(i), “wb”) as f:
               f.write(content)
           images.append(image_url)
       print(images)
       await browser.close()

cardlinks = [ 
  "https://money.usnews.com/credit-cards/alliant-credit-union/alliant-cashback-visa-signature-card",
  "https://money.usnews.com/credit-cards/american-express/amazon-business-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/amazon-business-prime-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/american-express-business-gold-card",
  "https://money.usnews.com/credit-cards/american-express/american-express-cash-magnet-card",
  "https://money.usnews.com/credit-cards/american-express/american-express-gold-card",
  "https://money.usnews.com/credit-cards/american-express/american-express-green-card",
  "https://money.usnews.com/credit-cards/american-express/amex-everyday-preferred-credit-card",
  "https://money.usnews.com/credit-cards/american-express/blue-cash-everyday-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/blue-cash-preferred-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/blue-from-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/business-green-rewards-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-blue-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-gold-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-gold-business-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-platinum-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-platinum-business-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-reserve-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/delta-skymiles-reserve-business-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/hilton-honors-american-express-aspire-card",
  "https://money.usnews.com/credit-cards/american-express/hilton-honors-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/hilton-honors-american-express-surpass-card",
  "https://money.usnews.com/credit-cards/american-express/macys-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/marriott-bonvoy-bevy-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/marriott-bonvoy-brilliant-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/marriott-bonvoy-business-american-express-card",
  "https://money.usnews.com/credit-cards/american-express/the-american-express-blue-business-cash-card",
  "https://money.usnews.com/credit-cards/american-express/the-blue-business-plus-credit-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/the-business-platinum-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/the-hilton-honors-american-express-business-card",
  "https://money.usnews.com/credit-cards/american-express/the-platinum-card-from-american-express",
  "https://money.usnews.com/credit-cards/american-express/the-plum-card-from-american-express",
  "https://money.usnews.com/credit-cards/applied-bank/applied-bank-secured-visa-gold-preferred-card",
  "https://money.usnews.com/credit-cards/bank-of-america/alaska-airlines-business-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/alaska-airlines-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bankamericard-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bankamericard-secured-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-allegiant-world-mastercard-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-business-advantage-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-business-advantage-travel-rewards-world-mastercard-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-cash-rewards-credit-card-for-students",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-celebrity-cruises-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-customized-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-norwegian-cruise-line-world-mastercard",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-platinum-plus-mastercard-business-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-premium-rewards-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-royal-caribbean-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-sandals-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-travel-rewards-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-travel-rewards-credit-card-for-students",
  "https://money.usnews.com/credit-cards/bank-of-america/bank-of-america-unlimited-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/bank-of-america/virgin-atlantic-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/aadvantage-aviator-red-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/bluegreen-rewards-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/carnival-world-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/frontier-airlines-world-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/hawaiian-airlines-business-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/holland-america-line-rewards-visa-card",
  "https://money.usnews.com/credit-cards/barclaycard/jetblue-business-card",
  "https://money.usnews.com/credit-cards/barclaycard/jetblue-plus-card",
  "https://money.usnews.com/credit-cards/barclaycard/miles--more-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/barclaycard/priceline-rewards-visa-card",
  "https://money.usnews.com/credit-cards/barclaycard/princess-cruises-rewards-visa-card",
  "https://money.usnews.com/credit-cards/barclaycard/wyndham-rewards-earner-card",
  "https://money.usnews.com/credit-cards/brex/brex--card",
  "https://money.usnews.com/credit-cards/capital-bank/opensky-secured-visa-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-platinum-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-platinum-secured-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-quicksilver-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-quicksilverone-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-quicksilver-secured-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-quicksilver-student-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-savor-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-savorone-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-savorone-student-cash-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-spark-cash-select-for-business",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-spark-classic-for-business",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-spark-miles-for-business",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-ventureone-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-venture-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-venture-x-rewards-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/capital-one-walmart-rewards-mastercard",
  "https://money.usnews.com/credit-cards/capital-one/kohls-credit-card",
  "https://money.usnews.com/credit-cards/capital-one/rei-coop-mastercard",
  "https://money.usnews.com/credit-cards/chase/aer-lingus-visa-signature-card",
  "https://money.usnews.com/credit-cards/chase/aeroplan-credit-card",
  "https://money.usnews.com/credit-cards/chase/amazon-rewards-visa-signature-card",
  "https://money.usnews.com/credit-cards/chase/british-airways-visa-signature-card",
  "https://money.usnews.com/credit-cards/chase/chase-freedom-unlimited",
  "https://money.usnews.com/credit-cards/chase/chase-sapphire-preferred-card",
  "https://money.usnews.com/credit-cards/chase/chase-sapphire-reserve",
  "https://money.usnews.com/credit-cards/chase/chase-slate-edge",
  "https://money.usnews.com/credit-cards/chase/disney-premier-visa-card",
  "https://money.usnews.com/credit-cards/chase/doordash-rewards-mastercard",
  "https://money.usnews.com/credit-cards/chase/iberia-visa-signature-card",
  "https://money.usnews.com/credit-cards/chase/ihg-one-rewards-premier-business-credit-card",
  "https://money.usnews.com/credit-cards/chase/ihg-one-rewards-premier-credit-card",
  "https://money.usnews.com/credit-cards/chase/ihg-one-rewards-traveler-credit-card",
  "https://money.usnews.com/credit-cards/chase/ink-business-cash-credit-card",
  "https://money.usnews.com/credit-cards/chase/ink-business-preferred-credit-card",
  "https://money.usnews.com/credit-cards/chase/ink-business-premier-credit-card",
  "https://money.usnews.com/credit-cards/chase/ink-business-unlimited-credit-card",
  "https://money.usnews.com/credit-cards/chase/instacart-mastercard",
  "https://money.usnews.com/credit-cards/chase/southwest-rapid-rewards-performance-business-credit-card",
  "https://money.usnews.com/credit-cards/chase/southwest-rapid-rewards-plus-credit-card",
  "https://money.usnews.com/credit-cards/chase/southwest-rapid-rewards-premier-business-credit-card",
  "https://money.usnews.com/credit-cards/chase/southwest-rapid-rewards-premier-credit-card",
  "https://money.usnews.com/credit-cards/chase/southwest-rapid-rewards-priority-credit-card",
  "https://money.usnews.com/credit-cards/chase/united-business-card",
  "https://money.usnews.com/credit-cards/chase/united-club-infinite-card",
  "https://money.usnews.com/credit-cards/chase/united-explorer-card",
  "https://money.usnews.com/credit-cards/chase/united-gateway-card",
  "https://money.usnews.com/credit-cards/chase/united-quest-card",
  "https://money.usnews.com/credit-cards/chase/world-of-hyatt-business-credit-card",
  "https://money.usnews.com/credit-cards/citi/american-airlines-aadvantage-mileup",
  "https://money.usnews.com/credit-cards/citi/citi--aadvantage-executive-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/citi/citi-aadvantage-platinum-select-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/citi/citibusiness-aadvantage-platinum-select-world-mastercard",
  "https://money.usnews.com/credit-cards/citi/citi-custom-cash-card",
  "https://money.usnews.com/credit-cards/citi/citi-diamond-preferred-card",
  "https://money.usnews.com/credit-cards/citi/citi-double-cash-card",
  "https://money.usnews.com/credit-cards/citi/citi-premier-card",
  "https://money.usnews.com/credit-cards/citi/citi-prestige-credit-card",
  "https://money.usnews.com/credit-cards/citi/citi-rewards-card",
  "https://money.usnews.com/credit-cards/citi/citi-secured-mastercard",
  "https://money.usnews.com/credit-cards/citi/citi-simplicity-card",
  "https://money.usnews.com/credit-cards/citi/costco-anywhere-visa-card-by-citi",
  "https://money.usnews.com/credit-cards/citi/my-best-buy-visa-card",
  "https://money.usnews.com/credit-cards/citizens-bank/citizens-cash-back-plus-world-mastercard",
  "https://money.usnews.com/credit-cards/comenity-capital-bank/lands-end-visa-credit-card",
  "https://money.usnews.com/credit-cards/commerce-bank/commerce-bank-secured-visa-credit-card",
  "https://money.usnews.com/credit-cards/commerce-bank/commerce-bank-voil-hotel-rewards-visa-signature",
  "https://money.usnews.com/credit-cards/commerce-bank/special-connections-credit-card",
  "https://money.usnews.com/credit-cards/credit-one-bank/credit-one-bank-american-express-card",
  "https://money.usnews.com/credit-cards/credit-one-bank/credit-one-bank-platinum-rewards-visa",
  "https://money.usnews.com/credit-cards/credit-one-bank/credit-one-bank-platinum-rewards-visa-with-no-annual-fee",
  "https://money.usnews.com/credit-cards/credit-one-bank/credit-one-bank-visa-cash-back-rewards",
  "https://money.usnews.com/credit-cards/deserve/deserve-edu-mastercard-for-students",
  "https://money.usnews.com/credit-cards/discover/discover-it-balance-transfer",
  "https://money.usnews.com/credit-cards/discover/discover-it-cash-back",
  "https://money.usnews.com/credit-cards/discover/discover-it-chrome",
  "https://money.usnews.com/credit-cards/discover/discover-it-miles",
  "https://money.usnews.com/credit-cards/discover/discover-it-secured-credit-card",
  "https://money.usnews.com/credit-cards/discover/discover-it-student-cash-back",
  "https://money.usnews.com/credit-cards/discover/discover-it-student-chrome",
  "https://money.usnews.com/credit-cards/discover/nhl-discover-it",
  "https://money.usnews.com/credit-cards/fifth-third-bank/fifth-third-secured-card",
  "https://money.usnews.com/credit-cards/fifth-third-bank/truly-simple-credit-card",
  "https://money.usnews.com/credit-cards/first-bankcard/best-western-rewards-premium-mastercard",
  "https://money.usnews.com/credit-cards/first-bankcard/sun-country-airlines-visa-signature-card",
  "https://money.usnews.com/credit-cards/first-progress/first-progress-platinum-prestige-mastercard-secured-credit-card",
  "https://money.usnews.com/credit-cards/genesis-fs-card-services/destiny-mastercard",
  "https://money.usnews.com/credit-cards/genesis-fs-card-services/indigo-platinum-mastercard",
  "https://money.usnews.com/credit-cards/genesis-fs-card-services/milestone-gold-mastercard",
  "https://money.usnews.com/credit-cards/goldman-sachs-bank-usa",
  "https://money.usnews.com/credit-cards/goldman-sachs-bank-usa/apple-card",
  "https://money.usnews.com/credit-cards/hsbc/hsbc-premier-world-mastercard-credit-card",
  "https://money.usnews.com/credit-cards/luxury-card/mastercard-black-card",
  "https://money.usnews.com/credit-cards/luxury-card/mastercard-gold-card",
  "https://money.usnews.com/credit-cards/luxury-card/mastercard-titanium-card",
  "https://money.usnews.com/credit-cards/marcus/my-gm-rewards-mastercard",
  "https://money.usnews.com/credit-cards/mt-bank/mt-business-credit-card",
  "https://money.usnews.com/credit-cards/mt-bank/mt-business-rewards-credit-card",
  "https://money.usnews.com/credit-cards/mt-bank/mt-visa-credit-card",
  "https://money.usnews.com/credit-cards/mt-bank/mt-visa-credit-card-with-rewards",
  "https://money.usnews.com/credit-cards/mt-bank/mt-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/navy-federal-credit-union/navy-federal-nrewards-secured-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-businessoptions-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-cash-rewards-visa-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-core-visa-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-points-visa-business-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-points-visa-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-premier-traveler-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-travel-rewards-visa-business-credit-card",
  "https://money.usnews.com/credit-cards/pnc/pnc-visa-business-credit-card",
  "https://money.usnews.com/credit-cards/simmons-bank/simmons-rewards-visa-signature",
  "https://money.usnews.com/credit-cards/simmons-bank/simmons-visa",
  "https://money.usnews.com/credit-cards/state-department-federal-credit-union/sdfcu-savings-secured-visa-platinum-card",
  "https://money.usnews.com/credit-cards/synchrony-bank/bp-visa-credit-card",
  "https://money.usnews.com/credit-cards/synchrony-bank/lowes-advantage-card",
  "https://money.usnews.com/credit-cards/synchrony-bank/real-rewards-credit-card-by-american-eagle-and-aerie",
  "https://money.usnews.com/credit-cards/synchrony-bank/techron-advantage-visa-card",
  "https://money.usnews.com/credit-cards/synchrony-bank/verizon-visa-card",
  "https://money.usnews.com/credit-cards/td-bank/target-redcard",
  "https://money.usnews.com/credit-cards/td-bank/td-business-solutions-credit-card",
  "https://money.usnews.com/credit-cards/td-bank/td-cash-credit-card",
  "https://money.usnews.com/credit-cards/td-bank/td-first-class-visa-signature-credit-card",
  "https://money.usnews.com/credit-cards/the-bank-of-missouri/fit-platinum-mastercard",
  "https://money.usnews.com/credit-cards/upgrade/upgrade-cash-rewards-visa",
  "https://money.usnews.com/credit-cards/usaa/usaa-cashback-rewards-plus-american-express-card",
  "https://money.usnews.com/credit-cards/usaa/usaa-preferred-cash-rewards-visa-signature-card",
  "https://money.usnews.com/credit-cards/usaa/usaa-rate-advantage-visa-platinum-card",
  "https://money.usnews.com/credit-cards/usaa/usaa-rewards-american-express-card",
  "https://money.usnews.com/credit-cards/usaa/usaa-rewards-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/skypass-visa-business-card",
  "https://money.usnews.com/credit-cards/us-bank/skypass-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-altitude-connect-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-altitude-go-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-business-leverage-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-business-triple-cash-rewards-world-elite-mastercard",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-cash-visa-signature-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-flexperks-gold-american-express-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-secured-visa-card",
  "https://money.usnews.com/credit-cards/us-bank/us-bank-visa-platinum-card",
  "https://money.usnews.com/credit-cards/webbank/petal--no-annual-fee-visa-credit-card",
  "https://money.usnews.com/credit-cards/webbank/petal--cash-back-no-fees-visa-credit-card",
  "https://money.usnews.com/credit-cards/wells-fargo/choice-privileges-mastercard",
  "https://money.usnews.com/credit-cards/wells-fargo/hotelscom-rewards-visa-credit-card",
  "https://money.usnews.com/credit-cards/wells-fargo/wells-fargo-active-cash-card",
  "https://money.usnews.com/credit-cards/wells-fargo/wells-fargo-autograph-card",
  "https://money.usnews.com/credit-cards/wells-fargo/wells-fargo-business-elite-card",
  "https://money.usnews.com/credit-cards/wells-fargo/wells-fargo-business-platinum-credit-card",
  "https://money.usnews.com/credit-cards/wells-fargo/wells-fargo-reflect-card"
]
